[5월] 김형진 / 나만의 도커 컴포즈 파일 콘테스트
drum-grammer/docker-pro pull request #32
Opened 2024-05-14 10:37 UTC by jinkimmy

도커 컴포즈 작업 파일을 PR 보냅니다. 그러나, 권한이 없어 Reviewers, Assignees, Labels 를 등록하지 못했습니다. 일단, Issues에 댓글로 아이디('jinkimmy')를 등록했습니다.

2024-05-15 01:32 UTC, drum-grammer requested changes
streamlit을 사용하셨군요 ㅎㅎ
뭔가 LLM을 활용한 채팅 서비스 같군요 ㅎㅎ 🙌
다른 분들도 이해할 수 있게 간단한 README 를 추가해주시고
chat.py 및 requirements.txt 파일도 함께 올려 주실 수 있나요?

2024-05-15 01:33 UTC, drum-grammer commented
권한 추가 했습니다.

2024-05-15 14:00 UTC, jinkimmy commented
chat.py 및 requirements.txt 파일과 함께 README 도 추가했습니다.

2024-05-17 23:45 UTC, drum-grammer commented
고생하셨습니다~

2024-05-17 23:45 UTC, merged